### ISSUE TITLE
Official abbreviation

### ISSUE THREAD

**Issue by xbony2** [Darkhax-Minecraft/Tesla#35]
What is the official abbreviation for Tesla? Like RF for Redstone Flux, EU for Energy Units, etc. I've seen simply "T" used a lot, although I think I've seen other stuff like "TESLA" and "TE" and whatnot. As a mod documenter, this is pretty important for me :P

**Comment by Prospector** [comment]
The official abbreviation right now is T. I think this should be a discussion though, what works best? Personally, I don't use an abbreviation in my mod, because T looks dumb. I just write out Tesla.

Which looks best, and makes the most sense?
- 100/100 Tesla
- 100/100 TESLA
- 100/100 T
- 100/100 TE (As TEsla or Tesla Energy)
- 100/100 TS
- 100/100 TL
- 100/100 TU (Tesla Units)

and my personal favourite (/s)
- 100/100 TP (Tesla Power aka Toilet Paper)

**Comment by Darkhax** [comment]
I personally prefer T however people like @ProfessorProspector are likely planning my assassination because of that lol. I also like TL, not a huge fan of the others though. What do the rest of you think?

**Comment by gigabit101** [comment]
Why not just use notRF ;-)

**Comment by RogueLogix** [comment]
TP in my opinion.

**Comment by adrwa** [comment]
imo.. T

_runs_

**Comment by mallrat208** [comment]
While T is to the point, or Tesla, the lower case t is already a common abbreviation for ticks. It may be confusing for some people to see something represented as T/t.

A two letter abbreviation like TL  may be better

**Comment by Prospector** [comment]
TL works. I like it.

**Comment by RogueLogix** [comment]
2 letters definitely, just look at previous (1.7.10) apis RF, MJ, EU, AE, etc. they all have two letters. @darkhax really needs to make the decision though.

**Comment by adrwa** [comment]
why does tesla have to be one of many? cant it be original? @killerall5385

**Comment by RogueLogix** [comment]
tesla is original and one of many. it is very different from all other apis, but it is still a power api. Not to mention, as you most likely know, power has been in minecraft for a long time.

**Comment by Darkhax** [comment]
All of the two letter units make sense, because they describe two letter things. Tesla's power units are called tesla(s) so a two letter abrv. does not work.

**Comment by Prospector** [comment]
which is why I suggested TU (Tesla Units), as it would make the most sense.

**Comment by adrwa** [comment]
i personally think T but if T wont do TU is the next best thing

**Comment by shadowfacts** [comment]
I think "T" would be the best abbreviation, but IMO standardizing on just using "Tesla" and not having an abbreviation would be best. Tesla is 5 characters long (only three characters longer than any 2-char abbreviation). RF is shortened to "RF" instead of "Redstone Flux" because "Redstone Flux" is long and unwieldy to write often, but "Tesla" doesn't have this problem.

**Comment by Prospector** [comment]
And nobody's gonna go around saying "I got 100 Ts", they're gonna say "I got 100 tesla"

**Comment by Darkhax** [comment]
After taking everything into consideration, I have decided on the official standard for power units. The full name should be the default. So `123 / 2000 Tesla` however in situations where space is limited and those extra three characters matter, a T will suffice. The opposition will likely say that the extra T bit will cause confusion, however I don't believe there is a reasonable case for this.
